### ISSUE TITLE
pydantic.errors.PydanticImportError: `BaseSettings` has been moved

### ISSUE THREAD

**Issue by hirefrank** [long2ice/meilisync#23]
`$ meilisync --help`

Alamalinux 9.

LMK if you have any ideas on how to resolve -- thx

```
Traceback (most recent call last):
  File "/srv/proj/.venv/bin/meilisync", line 5, in <module>
    from meilisync.main import app
  File "/srv/proj/.venv/lib64/python3.9/site-packages/meilisync/main.py", line 8, in <module>
    from meilisync.discover import get_progress, get_source
  File "/srv/proj/.venv/lib64/python3.9/site-packages/meilisync/discover.py", line 7, in <module>
    from meilisync import progress, source
  File "/srv/proj/.venv/lib64/python3.9/site-packages/meilisync/source/__init__.py", line 4, in <module>
    from meilisync.settings import Sync
  File "/srv/proj/.venv/lib64/python3.9/site-packages/meilisync/settings.py", line 3, in <module>
    from pydantic import BaseModel, BaseSettings, Extra
  File "/srv/proj/.venv/lib64/python3.9/site-packages/pydantic/__init__.py", line 218, in __getattr__
    return _getattr_migration(attr_name)
  File "/srv/proj/.venv/lib64/python3.9/site-packages/pydantic/_migration.py", line 294, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.
```

**Comment by long2ice** [comment]
Try latest source code

**Comment by hirefrank** [comment]
Does `pip install meilisync` not pull the latest?

**Comment by long2ice** [comment]
No, not release

**Comment by hirefrank** [comment]
Ah got it. Thx

**Comment by hirefrank** [comment]
Apologies for being dense -- how do I use the code in the repo? Do I need to build it first?

**Comment by sanders41** [comment]
To install the dev branch:

```sh
python -m pip install git+https://github.com/long2ice/meilisync.git@dev
```

**Comment by hirefrank** [comment]
Thank you
